require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/BlockLength:
  Max: 10
  Exclude:
    - 'spec/**/*.rb'
    - 'example/**/*.rb'
    - rspec_flat_error_formatter.gemspec

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Enabled: 20

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'example/**/*.rb'

RSpec/ExpectActual:
  Exclude:
    - 'example/**/*.rb'
