language: ruby
cache: bundler
before_install: gem install bundler -v 1.16.1

before_script:
  - bundle exec rubocop --config .rubocop.yml

script:
  - bundle exec rspec

notifications:
  email:
    on_success: never
    on_failure: never
