language: ruby
cache: bundler
before_install: gem install bundler -v 1.16.1

# we're running the rubocop in "before_script" hook to fail the build immediately and not waste time on running the "script"
before_script:
  - bundle exec rubocop --config .rubocop.yml

script:
  - bundle exec rspec

notifications:
  email:
    on_success: never
    on_failure: never
